n1= input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type))
print('É um número? {}'.format(n1.isnumeric()))
print('É alfabético?{}'.format(n1.isalpha()))
print('É u alfanumerico? {}'.format(n1.isalnum()))
print('Esta em maiusculas? {}'.format(n1.isupper()))
print('Esta em minusculas:{}'.format(n1.islower()))
print('Está capitalizada?{} '.format(n1.istitle()))
